zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null
  ignore_path: null

email:
  sender: gaoge92021@163.com
  receiver: gaoge92021@163.com
  smtp_server: smtp.163.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: Qwen/Qwen3-8B
    extra_body:
      enable_thinking: false
  language: Chinese

source:
  arxiv:
    category: ["cs.CR","cs.AI","cs.LG","cs.CL"]
    include_cross_list: false
  eprint:
    category: ["Cryptographic protocols","Secret-key cryptography","Public-key cryptography","Attacks and cryptanalysis"]

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv','eprint']
  send_empty: false
  max_paper_num: 20
  reranker: local
